package game1.pkg1.support;

import java.util.Map;

/**
 *
 * @author acob1
 */
public enum Mechanic {
    F_DAMAGE1, F_DAMAGE2, F_DAMAGE3, F_DAMAGE3SPLASH, F_DAMAGEALL, F_DAMAGEALLBUTME,        //flat damage
    O_DAMAGE1, O_DAMAGE2, O_DAMAGE3, O_DAMAGE3SPLASH, O_DAMAGEALL, O_DAMAGEALLBUTME,        //order damage
    A_DAMAGE1, A_DAMAGE2, A_DAMAGE3, A_DAMAGE3SPLASH, A_DAMAGEALL, A_DAMAGEALLBUTME,        //animus damage
    H_DAMAGE1, H_DAMAGE2, H_DAMAGE3, H_DAMAGE3SPLASH, H_DAMAGEALL, H_DAMAGEALLBUTME,        //honed damage
    HEAL1, HEAL3,
    REVIVE1,
    SLOW_ONCE, QUICKEN_ONCE, CORRUPT_ONCE, STUN_ONCE,
    SLOW_LONG, QUICKEN_LONG, CORRUPT_LONG, STUN_LONG;
}
